import 'package:get/get.dart';

class Mylocal implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en": {
          "welcome": "Welcome",
          "system_name": "in The Task System",
          "logoff": "LogOff",
          "login": "LOGIN",
          "pin_hent": "PIN Number",
          "pin_valid": "PIN Number is required",
          "loginpage_valid": "PIN Number is required",
          "loginpage_valid_t": "error masege",
          "loginpage_valid_m": "the pin you enter it is not existing",
          "datbase_error": "please check the database name and the url ",
          "back": "back",
          "db_valid": "the Database name is required ",
          "db_hent": "DataBase name",
          "url_hent": "the Url",
          "url_valid": "the Url is required ",
          "save": "save",
          "no_tasks": "there are no current tasks",
          "car_details": "Car Details",
          "custmer_name": "Customer Name",
          "phone_number": "Phone Number",
          "Car_Panel": "Car Panel No",
          "typecar": " Car Type ",
          "branch": "Branch",
          "tasks": "Tasks",
          "state": "State",
          "price": "Price",
          "type": "Type",
          "service": "Service",
          "complet": "complete",
          "uncomplet": "uncomplete",
          "unselect_taske": "there are no compleed tasks",
          "settings": "settings",
          "change_database": "change database",
          "language": "language",
          "Done": "Done",
          "arabic": "arabic",
          "english": "english",
          "signup": "Sign Up",
          "Panelno": "Panel no:",
          "carType": "Type: ",
          "workno": "work no: ",
          "new": "NEW",
          "start": "start",
          "processing": 'processing',
          "nophone": "no phone",
          "update": "update",
          "serverconction": "Server Connection",
          "conction": "Connection",
          "conctionsucc": "Connected successfully",
          "adminlogin": "adminlogin",
          "username": "username",
          "password": "password",
          "addimageforemployee": "Add Image for Employee",
          "sendphoto": "Approval and sending the image to the server",
          "changephoto": "click here to change the image",
          "takephoto": "click here to take the image",
          "takephoto2": "Add Image for Another Employee",
          "changedata": "Change of Employee Data"
        },
        "ar": {
          "welcome": "أهلا وسهلا بكم",
          "system_name": "في نظام المهام",
          "logoff": "تسجيل الخروج",
          "login": "تسجيل الدخول",
          "pin_hent": "رقم PIN ",
          "pin_valid": "رقم PIN  مطلوب",
          "loginpage_valid_t": "رسالة خطأ",
          "loginpage_valid_m": "لايوجد حساب بهذا pin",
          "datbase_error": "يرجاء التأكد من اسم قاعدة البيانات او الرابط",
          "back": "رجوع",
          "db_valid": "اسم قاعده البيانات مطلوب",
          "db_hent": 'اسم قاعده البيانات',
          "url_hent": "رابط الموقع",
          "url_valid": "رابط الموقع مطلوب",
          "save": "حفظ",
          "no_tasks": "لا توجد مهام حاليه ",
          "": "تفاصيل السيارة",
          "custmer_name": "اسم العميل",
          "phone_number": "رقم الجوال",
          "Car_Panel": "رقم اللوحه",
          "typecar": "نوع السيارة",
          "branch": "الفرع",
          "tasks": "المهام",
          "state": "الحالة",
          "price": "السعر",
          "type": "نوعها",
          "service": "الخدمة",
          "complet": "اكمال",
          "uncomplet": " الغاء اكمال المهمه",
          "unselect_taske": "لا يوجد مهام مكتملة",
          "car_details": "تفاصيل السيارة",
          "settings": "الاعدادات",
          "change_database": "تغير database",
          "language": "اللغه",
          "Done": "تم",
          "arabic": "العربيه",
          "english": "الانجليزيه",
          "signup": "تسجيل دخول",
          "Panelno": "رقم اللوحه:",
          "carType": "النوع: ",
          "workno": "رقم العمل: ",
          "start": "البدء",
          "new": "جديده",
          "processing": 'جاري التنفيذ',
          "nophone": 'لا يوجد رقم',
          "update": "تحديث",
          "serverconction": "الاتصال بالسيرفير",
          "conction": "اتصال",
          "conctionsucc": "تم الاتصال بنجاح",
          "adminlogin": "تسجيل دخول كأدمن",
          "username": "اسم المستخدم",
          "password": "كلمه المرور",
          "addimageforemployee": "اضافه صوره لموظف",
          "sendphoto": "اعتماد وارسال الصوره للسيرفير",
          "takephoto": "انقر هنا لاخذ صوره",
          "changephoto": "انقر هنا تغير الصوره",
          "takephoto2": 'اضافه صوره لموظف اخر',
          "changedata": "تغير بيانات الموظفين"
        },
      };
}
